name: Build ZBDongle-E OpenThread RCP

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-container:
    name: Create build container image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    outputs:
      container_name: ${{ steps.read-repo-info.outputs.container_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read repository information
        id: read-repo-info
        shell: bash
        run: |
          image_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          tag_name=$(echo "${{ hashFiles('Dockerfile') }}" | cut -c-16)

          if docker manifest inspect ${{ env.REGISTRY }}/$image_name:$tag_name >/dev/null 2>&1; then
            build_image=false
          else
            build_image=true
          fi

          echo "build_image=$build_image" >> $GITHUB_OUTPUT
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "image_name=$image_name" >> $GITHUB_OUTPUT
          echo "container_name=${{ env.REGISTRY }}/$image_name:$tag_name" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.read-repo-info.outputs.build_image == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build container
        if: steps.read-repo-info.outputs.build_image == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.read-repo-info.outputs.container_name }}

  build-firmware:
    name: Build ZBDongle-E Firmware

    needs:
      - build-container

    runs-on: ubuntu-latest

    container:
      image: ${{ needs.build-container.outputs.container_name }}
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install SDK extensions
        shell: bash
        run: |
          for sdk in /*_sdk_*; do
            slc signature trust --sdk "$sdk"

            ln -sf "$PWD/gecko_sdk_extensions" "$sdk"/extension

            for ext in "$sdk"/extension/*/; do
              slc signature trust --sdk "$sdk" --extension-path "$ext"
            done
          done

      - name: Build firmware
        shell: bash
        continue-on-error: true
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          sdk_args=""
          for sdk in /*_sdk*; do
            sdk_args="$sdk_args --sdk $sdk"
          done

          toolchain_args=""
          for tc in /opt/*arm-none-eabi*; do
            toolchain_args="$toolchain_args --toolchain $tc"
          done

          python3 tools/build_project.py \
            $sdk_args \
            $toolchain_args \
            --manifest manifests/sonoff/zbdonglee_openthread_rcp.yaml \
            --build-dir build \
            --build-system makefile \
            --output-dir outputs \
            --output gbl \
            --output hex \
            --output out

      - name: Upload build directory
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-directory
          path: build
          if-no-files-found: warn
          compression-level: 9

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firmware-output
          path: outputs
          if-no-files-found: warn
          compression-level: 9

      - name: Fail workflow if build failed
        if: failure()
        run: exit 1
