      - name: Build firmware
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          sdk_args=""
          for sdk in /*_sdk*; do
            sdk_args="$sdk_args --sdk $sdk"
          done

          toolchain_args=""
          for tc in /opt/*arm-none-eabi*; do
            toolchain_args="$toolchain_args --toolchain $tc"
          done

          python3 tools/build_project.py \
            $sdk_args \
            $toolchain_args \
            --manifest manifests/sonoff/zbdonglee_openthread_rcp.yaml \
            --build-dir build \
            --build-system makefile \
            --output-dir outputs \
            --output gbl \
            --output hex \
            --output out

      - name: Upload build directory
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-directory
          path: build
          if-no-files-found: warn
          compression-level: 9

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firmware-output
          path: outputs
          if-no-files-found: warn
          compression-level: 9
